### ISSUE TITLE
OP-004: Clarify request status communication model between server and client

### ISSUE THREAD

**Issue by amortensen** [dotswg/dots-requirements#12]
In 2.2, OP-004 requires a means for servers to report the status of client-requested actions. Per Dave Dolson, this requirement does not make sufficiently clear how that status is communicated.

**Comment by amortensen** [comment]
@dcdolson Do the changes from PR https://github.com/dotswg/dots-requirements/pull/26 sufficiently address this concern?

**Comment by dcdolson** [comment]
This is a lot more precise. Thanks.
