### ISSUE TITLE
OP-004: Clarify DOTS server's responsibilities after receiving a client request to cease mitigation

### ISSUE THREAD

**Issue by amortensen** [dotswg/dots-requirements#13]
Per Dave Dolson, what is required of the DOTS server after receiving a client request to cease mitigation is not sufficiently clear. The current text says the server "MUST cease mitigation activity as quickly as possible," but also notes server wants to avoid the impact of a client rapidly toggling mitigation.

The requirement should make clear how long the server may maintain a requested mitigation, and at what point the client may consider its responsibility for the mitigation at an end.

**Comment by dcdolson** [comment]
Cost was also mentioned. I think this means if there is a financial relationship, client stops paying when requesting mitigation cease.
