### ISSUE TITLE
OP-006: Establish required and optional mitigation scope types

### ISSUE THREAD

**Issue by amortensen** [dotswg/dots-requirements#15]
From Dave Dolson:

OP-006. I would like to see all of specific scopes precisely defined as required or optional, but not as examples. Let’s argue about which scopes are mandatory or optional  (or extendable) at this requirements phase.

**Comment by dcdolson** [comment]
I propose CIDR IPv4 and IPv6 are required.

**Comment by amortensen** [comment]
See PR 22: https://github.com/dotswg/dots-requirements/pull/22
