### ISSUE TITLE
Mitigation scope: clarify what Domain Names means

### ISSUE THREAD

**Issue by dcdolson** [dotswg/dots-requirements#32]
In OP-006, 
 *  Domain names [RFC1035]

One might interpret this as filtering DNS (I don't think intended).
It is unclear how this is converted into a packet filter. DNS lookup to get the addresses to filter?

Similar question for Uniform Resource Identifiers. Does this mean URL filtering?

**Comment by amortensen** [comment]
Addressed in PR #38
